export type OrderDetail = {
  order_id: string;
  sku: string;
  name: string;
  date: string;
  logistic_type: string;
  value: string;
  quantity: number;
  total_value: number;
  sale_fee: string;
  shipping_price: string;
  shipping_payed: string;
  shipping_discount: number;
  cost: number;
  total_cost: number;
  tax: number;
  income: number;
  tax_percentage: number;
  profit_value: number;
  profit_sale: number;
  profit_item: number;
  is_cancel: boolean;
};

export type OrderGroup = {
  order_id: string;
  sku: string;
  name: string;
  value: string;
  quantity: number;
  total_value: number;
  sale_fee: string;
  shipping_price: string;
  shipping_payed: string;
  shipping_discount: number;
  cost: number;
  total_cost: number;
  tax: number;
  income: number;
  tax_percentage: number;
  profit_value: number;
  profit_sale: number;
  profit_item: number;
  orders_detail: OrderDetail[];
};

export type Announcement = {
  ads_id: string;
  name: string;
  sku: string;
  modality: string;
  value: string;
  quantity: number;
  total_value: number;
  sale_fee: number;
  shipping_price: number;
  shipping_payed: number;
  shipping_discount: number;
  cost: number;
  total_cost: number;
  tax: number;
  income: number;
  profit_value: number;
  profit_sale: number;
  profit_item: number;
  is_registered: boolean;
  orders_detail: OrderDetail[];
  orders_group: OrderGroup[];
};
